# Generated by Django 5.0.2 on 2024-03-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
