# Generated by Django 5.0.2 on 2024-03-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_video_file_720p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file_720p',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='videos'),
        ),
    ]
