# Generated by Django 5.0.2 on 2024-03-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_video_file_720p'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file_480p',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
