# Generated by Django 4.0.6 on 2024-02-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_status_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='creatorId',
        ),
    ]
